---
title: "Coral Mapping"
author: "Ashley Holen"
format: html
editor: visual
---

```{r}
#packages
library(mapgl)
library(sf)
library(here)
library(RColorBrewer)
library(leaflet)
```

```{r}
#loading in data
coral <- read.csv(here('data/deep_sea_corals_43c0_dd36_9375.csv'))
```

```{r}
head(coral)
```

```{r}
#unique scientific names of coral in the dataset
unique(coral['ScientificName'])
```

```{r}
#subsetting just to the pearl harbor location
pearlharbor <- coral[coral$Locality == "Main Hawaiian Islands | Oahu Island, Pearl Harbor Defensive Sea Area", ]
```

```{r}
#unique vernacular names of coral in the dataset
unique(coral['VernacularNameCategory'])
```

```{r}
#subsetting just to invasive Octocoral (scientific name, Octocorallia)
octo <- subset(coral, ScientificName == "Octocorallia")
```

```{r}
head(octo)
```

```{r}
#sf for octocoral mapping
octo_sf <- st_as_sf(
  octo,
  coords = c("longitude..degrees_east.", "latitude..degrees_north."),   # <— long first, lat second
  crs = 4326
)
```

```{r}
#map of octocoral

#map bounds to HI
hawaii_bounds <- c(-161.1, 18.85, -154.8, 22.25)

mapboxgl(bounds = hawaii_bounds) |>
  add_circle_layer(
    id = "octo_points",
    source = octo_sf,
    circle_color = "purple",
    circle_radius = 5
  )
```

```{r}
#sf for all coral map
coral_sf <- st_as_sf(
  coral,
  coords = c("longitude..degrees_east.", "latitude..degrees_north."),   # <— long first, lat second
  crs = 4326
)
```

```{r}
#map of all hawaii coral by scientific name

hawaii_bounds <- c(-161.1, 18.85, -154.8, 22.25)

# palette based on species
pal <- colorFactor("Set2", coral_sf$VernacularNameCategory)

leaflet(coral_sf) |>
  addTiles() |>
  fitBounds(lng1 = hawaii_bounds[1],
            lat1 = hawaii_bounds[2],
            lng2 = hawaii_bounds[3],
            lat2 = hawaii_bounds[4]) |>
  addCircleMarkers(
    radius = 4,
    stroke = FALSE,
    fillOpacity = 0.9,
    color = ~pal(VernacularNameCategory)
  ) |>
  addLegend(
    pal = pal,
    values = ~VernacularNameCategory,
    title = "Coral Species",
    opacity = 1
  )

```
