```{r}
library(readr)
library(ggplot2)
library(maps)
library(dplyr)
library(gganimate)
library(plotly)
library(leaflet)
library(leaflet.extras)
```


```{r}
data <- read_csv("../data/deep_sea_corals_43c0_dd36_9375.csv")
data <- data[, -c(5)]
```

# depth plot
```{r}
world <- map_data("world")

ggplot() +
  geom_polygon(
    data = world,
    aes(x = long, y = lat, group = group),
    fill = "gray85", color = "white"
  ) +
  geom_point(
    data = data,
    aes(x = `longitude (degrees_east)`,
        y = `latitude (degrees_north)`,
        color = `DepthInMeters (m)`),
    size = 1
  ) +
  coord_fixed(1.3) +
  scale_color_viridis_c(option = "plasma") +
  labs(
    title = "depth",
    x = "lon",
    y = "lat",
    color = "Depth (m)"
  ) +
  theme_minimal() +
  coord_fixed(
      xlim = range(data$`longitude (degrees_east)`) + c(-1,1),
      ylim = range(data$`latitude (degrees_north)`) + c(-1,1)
    )

```

# Octocorallia

```{r}
matches <- data[grepl("octo", data$ScientificName, ignore.case = TRUE), ]
matches
data_octocorallia <- data[data$ScientificName == "Octocorallia", ]


data_octocorallia_plot <- data_octocorallia %>%
  mutate(
    lat = `latitude (degrees_north)`,
    lon = `longitude (degrees_east)`,
    depth = `DepthInMeters (m)`,
    year = as.numeric(format(ObservationDate, "%Y"))
  )

p <- ggplot() +
  geom_polygon(
    data = world,
    aes(x = long, y = lat, group = group),
    fill = "gray90", color = "gray50"
  ) +
  geom_point(
    data = data_octocorallia_plot,
    aes(x = lon, y = lat, color = depth, frame = year),
    size = 3, alpha = 0.7
  ) +
  scale_color_viridis_c(option = "plasma") +
  coord_fixed(1.3,
              xlim = range(data_octocorallia$`longitude (degrees_east)`) + c(-1,1),
              ylim = range(data_octocorallia$`latitude (degrees_north)`) + c(-1,1)
  ) +
  theme_minimal() +
  labs(title = "depth by year", color = "Depth (m)")

ggplotly(p) %>%
  animation_opts(
    frame = 1000,       # duration of frame 
    transition = 500,   # transition time 
    redraw = FALSE
  ) %>%
  animation_slider(
    currentvalue = list(prefix = "Year: "),
    hide = FALSE
  ) %>%
  animation_button(
    visible = FALSE       
  )
```


# barcharts - all species
```{r}
data_years <- data %>%
  mutate(
    year = as.numeric(format(ObservationDate, "%Y"))
  ) %>%
  filter(!is.na(year))
```


```{r}
ggplot(data_years, aes(x = year)) +
  geom_bar(fill = "steelblue") +
  theme_minimal() +
  labs(
    title = "Number of Coral Observations per Year",
    x = "Year",
    y = "Number of Observations"
  )
```
```{r}
ggplot() +
  geom_polygon(
    data = world,
    aes(x = long, y = lat, group = group),
    fill = "gray90",
    color = "gray50",
    linewidth = 0.2
  ) +
  geom_point(
    data = data_years,
    aes(
      x = `longitude (degrees_east)`,
      y = `latitude (degrees_north)`,
      color = year
    ),
    alpha = 0.6
  ) +
  scale_color_viridis_c() +
  theme_minimal() +
  labs(
    title = "Spatial Distribution of Coral Observations Over Time",
    x = "Longitude",
    y = "Latitude",
    color = "Year"
  ) +
  coord_fixed(1.3,
              xlim = range(data_octocorallia$`longitude (degrees_east)`) + c(-1,1),
              ylim = range(data_octocorallia$`latitude (degrees_north)`) + c(-1,1)
  )

```

```{r}
data_years %>%
  group_by(year) %>%
  summarise(species_richness = n_distinct(ScientificName)) %>%
  ggplot(aes(x = year, y = species_richness)) +
  geom_line(color = "purple") +
  geom_point(color = "purple") +
  theme_minimal() +
  labs(
    title = "Number of Unique Coral Species Observed per Year",
    x = "Year",
    y = "Species Count"
  )
```


